name: اصلاح واژه
description: اصلاح یا بهبود یک واژهٔ موجود
labels: ["correction"]
body:
  - type: input
    id: term
    attributes:
      label: نام واژه
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: نوع اصلاح
      options:
        - اشتباه در تعریف
        - اشتباه در ترجمه
        - اطلاعات ناقص
        - املایی
        - سایر
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: متن فعلی یا مشکل
    validations:
      required: true
  - type: textarea
    id: suggested
    attributes:
      label: پیشنهاد شما
    validations:
      required: true
  - type: textarea
    id: ref
    attributes:
      label: منبع
  - type: checkboxes
    id: agree
    attributes:
      label: توافق
      options:
        - label: مشارکتم تحت CC BY-SA 4.0 منتشر شود.
          required: true
