name: پیشنهاد واژهٔ جدید
description: افزودن واژه به فرهنگ
labels: ["new-term"]
body:
  - type: input
    id: fa
    attributes:
      label: واژهٔ فارسی
    validations:
      required: true
  - type: input
    id: en
    attributes:
      label: معادل انگلیسی
    validations:
      required: true
  - type: input
    id: fr
    attributes:
      label: معادل فرانسوی (اختیاری)
  - type: input
    id: de
    attributes:
      label: معادل آلمانی (اختیاری)
  - type: input
    id: ar
    attributes:
      label: معادل عربی (اختیاری)
  - type: input
    id: category
    attributes:
      label: دستهٔ تخصصی
    validations:
      required: true
  - type: textarea
    id: definition
    attributes:
      label: تعریف پیشنهادی
    validations:
      required: true
  - type: textarea
    id: standards
    attributes:
      label: استانداردها (هر کدام در یک خط)
  - type: input
    id: chapter
    attributes:
      label: فصل مرتبط در کتاب
  - type: checkboxes
    id: agree
    attributes:
      label: توافق
      options:
        - label: مشارکتم تحت CC BY-SA 4.0 منتشر شود.
          required: true
